<?php

use App\Core\Router;
use App\Modules\AdminModule\Controllers\AdminController;
use App\Modules\AdminModule\Middlewares\AdminAccessMiddleware;

return static function (Router $router): void {
    $adminMiddleware = [[AdminAccessMiddleware::class, 'handle']];

    $router->get('/admin', AdminController::class, 'dashboard', ['as' => 'admin.dashboard', 'middleware' => $adminMiddleware]);
    $router->get('/admin/users', AdminController::class, 'users', ['as' => 'admin.users', 'middleware' => $adminMiddleware]);
    $router->post('/admin/users/{user:\\d+}/roles', AdminController::class, 'assignRoles', ['as' => 'admin.users.roles', 'middleware' => $adminMiddleware]);
    $router->get('/admin/roles', AdminController::class, 'roles', ['as' => 'admin.roles', 'middleware' => $adminMiddleware]);
    $router->post('/admin/roles/{role:\\d+}/permissions', AdminController::class, 'syncPermissions', ['as' => 'admin.roles.permissions', 'middleware' => $adminMiddleware]);
    $router->get('/admin/pages', AdminController::class, 'pages', ['as' => 'admin.pages', 'middleware' => $adminMiddleware]);
    $router->post('/admin/pages', AdminController::class, 'savePage', ['as' => 'admin.pages.store', 'middleware' => $adminMiddleware]);
    $router->post('/admin/pages/{page:\\d+}/update', AdminController::class, 'updatePage', ['as' => 'admin.pages.update', 'middleware' => $adminMiddleware]);
    $router->post('/admin/pages/{page:\\d+}/publish', AdminController::class, 'publishPage', ['as' => 'admin.pages.publish', 'middleware' => $adminMiddleware]);
    $router->post('/admin/pages/{page:\\d+}/unpublish', AdminController::class, 'unpublishPage', ['as' => 'admin.pages.unpublish', 'middleware' => $adminMiddleware]);
    $router->post('/admin/pages/{page:\\d+}/delete', AdminController::class, 'deletePage', ['as' => 'admin.pages.delete', 'middleware' => $adminMiddleware]);
    $router->get('/admin/catalog', AdminController::class, 'catalog', ['as' => 'admin.catalog', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/categories', AdminController::class, 'saveCategory', ['as' => 'admin.catalog.categories.store', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/categories/{category:\\d+}/update', AdminController::class, 'updateCategory', ['as' => 'admin.catalog.categories.update', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/categories/{category:\\d+}/publish', AdminController::class, 'publishCategory', ['as' => 'admin.catalog.categories.publish', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/categories/{category:\\d+}/unpublish', AdminController::class, 'unpublishCategory', ['as' => 'admin.catalog.categories.unpublish', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/categories/{category:\\d+}/delete', AdminController::class, 'deleteCategory', ['as' => 'admin.catalog.categories.delete', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/products', AdminController::class, 'saveProduct', ['as' => 'admin.catalog.products.store', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/products/{product:\\d+}/update', AdminController::class, 'updateProduct', ['as' => 'admin.catalog.products.update', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/products/{product:\\d+}/publish', AdminController::class, 'publishProduct', ['as' => 'admin.catalog.products.publish', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/products/{product:\\d+}/draft', AdminController::class, 'draftProduct', ['as' => 'admin.catalog.products.draft', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/products/{product:\\d+}/archive', AdminController::class, 'archiveProduct', ['as' => 'admin.catalog.products.archive', 'middleware' => $adminMiddleware]);
    $router->post('/admin/catalog/products/{product:\\d+}/delete', AdminController::class, 'deleteProduct', ['as' => 'admin.catalog.products.delete', 'middleware' => $adminMiddleware]);
    $router->get('/admin/promotions', AdminController::class, 'promotions', ['as' => 'admin.promotions', 'middleware' => $adminMiddleware]);
    $router->post('/admin/promotions', AdminController::class, 'savePromotion', ['as' => 'admin.promotions.store', 'middleware' => $adminMiddleware]);
    $router->post('/admin/promotions/{promotion:\\d+}/update', AdminController::class, 'updatePromotion', ['as' => 'admin.promotions.update', 'middleware' => $adminMiddleware]);
    $router->post('/admin/promotions/{promotion:\\d+}/activate', AdminController::class, 'activatePromotion', ['as' => 'admin.promotions.activate', 'middleware' => $adminMiddleware]);
    $router->post('/admin/promotions/{promotion:\\d+}/deactivate', AdminController::class, 'deactivatePromotion', ['as' => 'admin.promotions.deactivate', 'middleware' => $adminMiddleware]);
    $router->post('/admin/promotions/{promotion:\\d+}/delete', AdminController::class, 'deletePromotion', ['as' => 'admin.promotions.delete', 'middleware' => $adminMiddleware]);
    $router->get('/admin/carts', AdminController::class, 'carts', ['as' => 'admin.carts', 'middleware' => $adminMiddleware]);
    $router->get('/admin/orders', AdminController::class, 'orders', ['as' => 'admin.orders', 'middleware' => $adminMiddleware]);
    $router->get('/admin/orders/{order:\\d+}', AdminController::class, 'order', ['as' => 'admin.orders.show', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/capture', AdminController::class, 'captureOrder', ['as' => 'admin.orders.capture', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/cancel', AdminController::class, 'cancelOrder', ['as' => 'admin.orders.cancel', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/refund', AdminController::class, 'refundOrder', ['as' => 'admin.orders.refund', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/reconcile', AdminController::class, 'reconcileOrder', ['as' => 'admin.orders.reconcile', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/pack', AdminController::class, 'packOrder', ['as' => 'admin.orders.pack', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/service-points', AdminController::class, 'servicePointsOrder', ['as' => 'admin.orders.service-points', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/book-shipment', AdminController::class, 'bookShipmentOrder', ['as' => 'admin.orders.book-shipment', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/ship', AdminController::class, 'shipOrder', ['as' => 'admin.orders.ship', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/sync-tracking', AdminController::class, 'syncTrackingOrder', ['as' => 'admin.orders.sync-tracking', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/cancel-shipment', AdminController::class, 'cancelShipmentOrder', ['as' => 'admin.orders.cancel-shipment', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/deliver', AdminController::class, 'deliverOrder', ['as' => 'admin.orders.deliver', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/entitlements/{entitlement:\\d+}/activate', AdminController::class, 'activateEntitlement', ['as' => 'admin.orders.entitlements.activate', 'middleware' => $adminMiddleware]);
    $router->post('/admin/orders/{order:\\d+}/entitlements/{entitlement:\\d+}/revoke', AdminController::class, 'revokeEntitlement', ['as' => 'admin.orders.entitlements.revoke', 'middleware' => $adminMiddleware]);
    $router->get('/admin/system', AdminController::class, 'system', ['as' => 'admin.system', 'middleware' => $adminMiddleware]);
    $router->get('/admin/operations', AdminController::class, 'operations', ['as' => 'admin.operations', 'middleware' => $adminMiddleware]);

    $router->get('/api/admin', AdminController::class, 'dashboard', ['as' => 'api.admin.dashboard', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/users', AdminController::class, 'users', ['as' => 'api.admin.users', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/users/{user:\\d+}/roles', AdminController::class, 'assignRoles', ['as' => 'api.admin.users.roles', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/roles', AdminController::class, 'roles', ['as' => 'api.admin.roles', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/roles/{role:\\d+}/permissions', AdminController::class, 'syncPermissions', ['as' => 'api.admin.roles.permissions', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/pages', AdminController::class, 'pages', ['as' => 'api.admin.pages', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/pages', AdminController::class, 'savePage', ['as' => 'api.admin.pages.store', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/pages/{page:\\d+}/update', AdminController::class, 'updatePage', ['as' => 'api.admin.pages.update', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/pages/{page:\\d+}/publish', AdminController::class, 'publishPage', ['as' => 'api.admin.pages.publish', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/pages/{page:\\d+}/unpublish', AdminController::class, 'unpublishPage', ['as' => 'api.admin.pages.unpublish', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/pages/{page:\\d+}/delete', AdminController::class, 'deletePage', ['as' => 'api.admin.pages.delete', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/catalog', AdminController::class, 'catalog', ['as' => 'api.admin.catalog', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/categories', AdminController::class, 'saveCategory', ['as' => 'api.admin.catalog.categories.store', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/categories/{category:\\d+}/update', AdminController::class, 'updateCategory', ['as' => 'api.admin.catalog.categories.update', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/categories/{category:\\d+}/publish', AdminController::class, 'publishCategory', ['as' => 'api.admin.catalog.categories.publish', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/categories/{category:\\d+}/unpublish', AdminController::class, 'unpublishCategory', ['as' => 'api.admin.catalog.categories.unpublish', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/categories/{category:\\d+}/delete', AdminController::class, 'deleteCategory', ['as' => 'api.admin.catalog.categories.delete', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/products', AdminController::class, 'saveProduct', ['as' => 'api.admin.catalog.products.store', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/products/{product:\\d+}/update', AdminController::class, 'updateProduct', ['as' => 'api.admin.catalog.products.update', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/products/{product:\\d+}/publish', AdminController::class, 'publishProduct', ['as' => 'api.admin.catalog.products.publish', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/products/{product:\\d+}/draft', AdminController::class, 'draftProduct', ['as' => 'api.admin.catalog.products.draft', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/products/{product:\\d+}/archive', AdminController::class, 'archiveProduct', ['as' => 'api.admin.catalog.products.archive', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/catalog/products/{product:\\d+}/delete', AdminController::class, 'deleteProduct', ['as' => 'api.admin.catalog.products.delete', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/promotions', AdminController::class, 'promotions', ['as' => 'api.admin.promotions', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/promotions', AdminController::class, 'savePromotion', ['as' => 'api.admin.promotions.store', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/promotions/{promotion:\\d+}/update', AdminController::class, 'updatePromotion', ['as' => 'api.admin.promotions.update', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/promotions/{promotion:\\d+}/activate', AdminController::class, 'activatePromotion', ['as' => 'api.admin.promotions.activate', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/promotions/{promotion:\\d+}/deactivate', AdminController::class, 'deactivatePromotion', ['as' => 'api.admin.promotions.deactivate', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/promotions/{promotion:\\d+}/delete', AdminController::class, 'deletePromotion', ['as' => 'api.admin.promotions.delete', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/carts', AdminController::class, 'carts', ['as' => 'api.admin.carts', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/orders', AdminController::class, 'orders', ['as' => 'api.admin.orders', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/orders/{order:\\d+}', AdminController::class, 'order', ['as' => 'api.admin.orders.show', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/capture', AdminController::class, 'captureOrder', ['as' => 'api.admin.orders.capture', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/cancel', AdminController::class, 'cancelOrder', ['as' => 'api.admin.orders.cancel', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/refund', AdminController::class, 'refundOrder', ['as' => 'api.admin.orders.refund', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/reconcile', AdminController::class, 'reconcileOrder', ['as' => 'api.admin.orders.reconcile', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/pack', AdminController::class, 'packOrder', ['as' => 'api.admin.orders.pack', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/service-points', AdminController::class, 'servicePointsOrder', ['as' => 'api.admin.orders.service-points', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/book-shipment', AdminController::class, 'bookShipmentOrder', ['as' => 'api.admin.orders.book-shipment', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/ship', AdminController::class, 'shipOrder', ['as' => 'api.admin.orders.ship', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/sync-tracking', AdminController::class, 'syncTrackingOrder', ['as' => 'api.admin.orders.sync-tracking', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/cancel-shipment', AdminController::class, 'cancelShipmentOrder', ['as' => 'api.admin.orders.cancel-shipment', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/deliver', AdminController::class, 'deliverOrder', ['as' => 'api.admin.orders.deliver', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/entitlements/{entitlement:\\d+}/activate', AdminController::class, 'activateEntitlement', ['as' => 'api.admin.orders.entitlements.activate', 'middleware' => $adminMiddleware]);
    $router->post('/api/admin/orders/{order:\\d+}/entitlements/{entitlement:\\d+}/revoke', AdminController::class, 'revokeEntitlement', ['as' => 'api.admin.orders.entitlements.revoke', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/system', AdminController::class, 'system', ['as' => 'api.admin.system', 'middleware' => $adminMiddleware]);
    $router->get('/api/admin/operations', AdminController::class, 'operations', ['as' => 'api.admin.operations', 'middleware' => $adminMiddleware]);
};
