<?php

declare(strict_types=1);

return [
    'CURRENCY' => 'SEK',
    'TAX' => [
        'RATE_BPS' => 2500,
    ],
    'SHIPPING' => [
        'DEFAULT_COUNTRY' => 'SE',
        'DEFAULT_OPTION' => 'postnord-service-point',
        'FLAT_RATE_MINOR' => 1490,
        'FREE_OVER_MINOR' => 50000,
        'CARRIERS' => [
            'postnord' => [
                'LABEL' => 'PostNord',
                'PORTAL_URL' => 'https://www.postnord.se/en/track-and-trace',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
            ],
            'instabox' => [
                'LABEL' => 'Instabox',
                'PORTAL_URL' => 'https://instabox.io',
                'ZONES' => ['SE'],
            ],
            'budbee' => [
                'LABEL' => 'Budbee',
                'PORTAL_URL' => 'https://budbee.com',
                'ZONES' => ['SE', 'NORDIC'],
            ],
            'bring' => [
                'LABEL' => 'Bring',
                'PORTAL_URL' => 'https://www.bring.se',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
            ],
            'dhl' => [
                'LABEL' => 'DHL',
                'PORTAL_URL' => 'https://www.dhl.com/se-en/home/tracking.html',
                'ZONES' => ['SE', 'NORDIC', 'EU', 'INTL'],
            ],
            'schenker' => [
                'LABEL' => 'Schenker',
                'PORTAL_URL' => 'https://www.dbschenker.com/se-en',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
            ],
            'earlybird' => [
                'LABEL' => 'Early Bird',
                'PORTAL_URL' => 'https://earlybird.se',
                'ZONES' => ['SE'],
            ],
            'airmee' => [
                'LABEL' => 'Airmee',
                'PORTAL_URL' => 'https://airmee.com',
                'ZONES' => ['SE'],
            ],
            'ups' => [
                'LABEL' => 'UPS',
                'PORTAL_URL' => 'https://www.ups.com/track',
                'ZONES' => ['SE', 'NORDIC', 'EU', 'INTL'],
            ],
        ],
        'TRACKING_APPS' => [
            'mina_paket' => [
                'LABEL' => 'Mina Paket',
                'COUNTRIES' => ['SE'],
                'CARRIERS' => ['postnord', 'instabox', 'budbee', 'bring', 'dhl', 'schenker', 'earlybird', 'airmee', 'ups'],
                'PLATFORMS' => ['iOS'],
                'NOTE' => 'Helpful when the tracking number is imported into the app.',
            ],
        ],
        'OPTIONS' => [
            'postnord-service-point' => [
                'LABEL' => 'PostNord Service Point',
                'CARRIER' => 'postnord',
                'SERVICE_CODE' => 'service_point',
                'SERVICE_LABEL' => 'Service Point',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 1490,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'instabox-locker' => [
                'LABEL' => 'Instabox Locker',
                'CARRIER' => 'instabox',
                'SERVICE_CODE' => 'locker',
                'SERVICE_LABEL' => 'Locker Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 990,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'budbee-box' => [
                'LABEL' => 'Budbee Box',
                'CARRIER' => 'budbee',
                'SERVICE_CODE' => 'locker',
                'SERVICE_LABEL' => 'Locker Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 1090,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'budbee-home' => [
                'LABEL' => 'Budbee Home',
                'CARRIER' => 'budbee',
                'SERVICE_CODE' => 'home',
                'SERVICE_LABEL' => 'Home Delivery',
                'ZONES' => ['SE', 'NORDIC'],
                'RATE_MINOR' => 1290,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
            'bring-service-point' => [
                'LABEL' => 'Bring Service Point',
                'CARRIER' => 'bring',
                'SERVICE_CODE' => 'service_point',
                'SERVICE_LABEL' => 'Service Point',
                'ZONES' => ['SE', 'NORDIC'],
                'RATE_MINOR' => 1390,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'dhl-service-point' => [
                'LABEL' => 'DHL Service Point',
                'CARRIER' => 'dhl',
                'SERVICE_CODE' => 'service_point',
                'SERVICE_LABEL' => 'Service Point',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
                'RATE_MINOR' => 1590,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'schenker-parcel' => [
                'LABEL' => 'Schenker Parcel',
                'CARRIER' => 'schenker',
                'SERVICE_CODE' => 'parcel',
                'SERVICE_LABEL' => 'Parcel Delivery',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
                'RATE_MINOR' => 1490,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'earlybird-mailbox' => [
                'LABEL' => 'Early Bird Mailbox',
                'CARRIER' => 'earlybird',
                'SERVICE_CODE' => 'mailbox',
                'SERVICE_LABEL' => 'Mailbox Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 790,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'airmee-home' => [
                'LABEL' => 'Airmee Home',
                'CARRIER' => 'airmee',
                'SERVICE_CODE' => 'home',
                'SERVICE_LABEL' => 'Evening Home Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 1690,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
            'ups-standard' => [
                'LABEL' => 'UPS Standard',
                'CARRIER' => 'ups',
                'SERVICE_CODE' => 'standard',
                'SERVICE_LABEL' => 'Standard Delivery',
                'ZONES' => ['EU', 'INTL'],
                'RATE_MINOR' => 2490,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
            'dhl-express' => [
                'LABEL' => 'DHL Express',
                'CARRIER' => 'dhl',
                'SERVICE_CODE' => 'express',
                'SERVICE_LABEL' => 'Express Delivery',
                'ZONES' => ['EU', 'INTL'],
                'RATE_MINOR' => 2990,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
        ],
    ],
    'DISCOUNT' => [
        'RATE_BPS' => 0,
        'MAX_MINOR' => 0,
    ],
    'PROMOTIONS' => [
        'VALKOMMEN10' => [
            'LABEL' => 'Valkommen 10%',
            'DESCRIPTION' => 'A gentle first-order style discount on the cart subtotal.',
            'TYPE' => 'percentage',
            'RATE_BPS' => 1000,
            'MAX_DISCOUNT_MINOR' => 3000,
            'MIN_SUBTOTAL_MINOR' => 5000,
            'ALLOWED_COUNTRIES' => ['SE', 'NO', 'DK', 'FI'],
            'ALLOWED_ZONES' => ['SE', 'NORDIC'],
        ],
        'START100' => [
            'LABEL' => 'Start 100 kr',
            'DESCRIPTION' => 'Fixed launch discount for larger baskets.',
            'TYPE' => 'fixed_amount',
            'AMOUNT_MINOR' => 10000,
            'MIN_SUBTOTAL_MINOR' => 15000,
            'ALLOWED_COUNTRIES' => ['SE'],
            'ALLOWED_ZONES' => ['SE'],
        ],
        'FRIFRAKT' => [
            'LABEL' => 'Fri Frakt',
            'DESCRIPTION' => 'Free shipping on service-point and other free-shipping eligible methods.',
            'TYPE' => 'free_shipping',
            'MIN_SUBTOTAL_MINOR' => 5000,
            'FREE_SHIPPING_ELIGIBLE_ONLY' => true,
            'ALLOWED_COUNTRIES' => ['SE'],
            'ALLOWED_ZONES' => ['SE'],
        ],
        'LOCKER49' => [
            'LABEL' => 'Locker 49 kr',
            'DESCRIPTION' => 'Reduces selected Swedish locker deliveries to 49 kr.',
            'TYPE' => 'shipping_fixed',
            'SHIPPING_RATE_MINOR' => 490,
            'ALLOWED_COUNTRIES' => ['SE'],
            'ALLOWED_ZONES' => ['SE'],
            'ALLOWED_CARRIERS' => ['instabox', 'budbee', 'postnord'],
            'ALLOWED_SHIPPING_OPTIONS' => ['instabox-locker', 'budbee-box', 'postnord-service-point'],
        ],
    ],
    'INVENTORY' => [
        'RESERVE_ON_CHECKOUT' => true,
        'RELEASE_ON_CANCEL' => true,
    ],
    'FULFILLMENT' => [
        'AUTO_READY_ON_CAPTURE' => true,
    ],
];
