<?php

declare(strict_types=1);

return [
    'CURRENCY' => 'SEK',
    'TAX' => [
        'RATE_BPS' => 2500,
    ],
    'DOCUMENTS' => [
        'VAT_RATE_BPS' => 2500,
        'SELLER_NAME' => 'LangelerMVC',
        'SELLER_VAT_ID' => '',
        'SELLER_ADDRESS' => '',
    ],
    'RETURNS' => [
        'WINDOW_DAYS' => 30,
        'ALLOW_EXCHANGES' => true,
        'AUTO_RESTOCK' => true,
    ],
    'SHIPPING' => [
        'DEFAULT_COUNTRY' => 'SE',
        'DEFAULT_OPTION' => 'postnord-service-point',
        'FLAT_RATE_MINOR' => 1490,
        'FREE_OVER_MINOR' => 50000,
        'INTEGRATION' => [
            'MODE' => 'reference',
            'ACTIVE_CARRIER' => 'postnord',
            'AUTO_BOOK_LABELS' => true,
            'LABEL_FORMAT' => 'pdf',
            'LABEL_BASE_URL' => 'https://shipments.langelermvc.test/labels',
            'API_BASE' => '',
            'API_KEY' => '',
            'USERNAME' => '',
            'PASSWORD' => '',
            'AUTH_SCHEME' => 'Bearer',
            'SERVICE_POINTS_URL' => '',
            'BOOKING_URL' => '',
            'TRACKING_URL' => '',
            'CANCELLATION_URL' => '',
            'TIMEOUT' => 30,
        ],
        'CARRIERS' => [
            'postnord' => [
                'LABEL' => 'PostNord',
                'PORTAL_URL' => 'https://www.postnord.se/en/track-and-trace',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
            ],
            'instabox' => [
                'LABEL' => 'Instabox',
                'PORTAL_URL' => 'https://instabox.io',
                'ZONES' => ['SE'],
            ],
            'budbee' => [
                'LABEL' => 'Budbee',
                'PORTAL_URL' => 'https://budbee.com',
                'ZONES' => ['SE', 'NORDIC'],
            ],
            'bring' => [
                'LABEL' => 'Bring',
                'PORTAL_URL' => 'https://www.bring.se',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
            ],
            'dhl' => [
                'LABEL' => 'DHL',
                'PORTAL_URL' => 'https://www.dhl.com/se-en/home/tracking.html',
                'ZONES' => ['SE', 'NORDIC', 'EU', 'INTL'],
            ],
            'schenker' => [
                'LABEL' => 'Schenker',
                'PORTAL_URL' => 'https://www.dbschenker.com/se-en',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
            ],
            'earlybird' => [
                'LABEL' => 'Early Bird',
                'PORTAL_URL' => 'https://earlybird.se',
                'ZONES' => ['SE'],
            ],
            'airmee' => [
                'LABEL' => 'Airmee',
                'PORTAL_URL' => 'https://airmee.com',
                'ZONES' => ['SE'],
            ],
            'ups' => [
                'LABEL' => 'UPS',
                'PORTAL_URL' => 'https://www.ups.com/track',
                'ZONES' => ['SE', 'NORDIC', 'EU', 'INTL'],
            ],
        ],
        'ADAPTERS' => [
            'postnord' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'PostNord',
                'REGIONS' => ['SE', 'NORDIC', 'EU'],
                'SERVICE_LEVELS' => ['service_point', 'home'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'instabox' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'Instabox',
                'REGIONS' => ['SE'],
                'SERVICE_LEVELS' => ['locker'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'SERVICE_POINTS_URL', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'budbee' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'Budbee',
                'REGIONS' => ['SE', 'NORDIC'],
                'SERVICE_LEVELS' => ['locker', 'home'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'SERVICE_POINTS_URL', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'bring' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'Bring',
                'REGIONS' => ['SE', 'NORDIC', 'EU'],
                'SERVICE_LEVELS' => ['service_point', 'home'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'SERVICE_POINTS_URL', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'dhl' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'DHL',
                'REGIONS' => ['SE', 'NORDIC', 'EU', 'INTL'],
                'SERVICE_LEVELS' => ['service_point', 'home', 'express'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'SERVICE_POINTS_URL', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'schenker' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'Schenker',
                'REGIONS' => ['SE', 'NORDIC', 'EU'],
                'SERVICE_LEVELS' => ['service_point', 'home'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'SERVICE_POINTS_URL', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'earlybird' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'Early Bird',
                'REGIONS' => ['SE'],
                'SERVICE_LEVELS' => ['mailbox'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'airmee' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'Airmee',
                'REGIONS' => ['SE'],
                'SERVICE_LEVELS' => ['home'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'BOOKING_URL', 'TRACKING_URL'],
            ],
            'ups' => [
                'ENABLED' => true,
                'MODE' => 'reference',
                'LABEL' => 'UPS',
                'REGIONS' => ['SE', 'NORDIC', 'EU', 'INTL'],
                'SERVICE_LEVELS' => ['home', 'standard', 'express'],
                'REQUIRED_SETTINGS' => ['API_BASE', 'API_KEY', 'BOOKING_URL', 'TRACKING_URL'],
            ],
        ],
        'TRACKING_APPS' => [
            'mina_paket' => [
                'LABEL' => 'Mina Paket',
                'COUNTRIES' => ['SE'],
                'CARRIERS' => ['postnord', 'instabox', 'budbee', 'bring', 'dhl', 'schenker', 'earlybird', 'airmee', 'ups'],
                'PLATFORMS' => ['iOS'],
                'NOTE' => 'Helpful when the tracking number is imported into the app.',
            ],
        ],
        'OPTIONS' => [
            'postnord-service-point' => [
                'LABEL' => 'PostNord Service Point',
                'CARRIER' => 'postnord',
                'SERVICE_CODE' => 'service_point',
                'SERVICE_LABEL' => 'Service Point',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 1490,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'instabox-locker' => [
                'LABEL' => 'Instabox Locker',
                'CARRIER' => 'instabox',
                'SERVICE_CODE' => 'locker',
                'SERVICE_LABEL' => 'Locker Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 990,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'budbee-box' => [
                'LABEL' => 'Budbee Box',
                'CARRIER' => 'budbee',
                'SERVICE_CODE' => 'locker',
                'SERVICE_LABEL' => 'Locker Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 1090,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'budbee-home' => [
                'LABEL' => 'Budbee Home',
                'CARRIER' => 'budbee',
                'SERVICE_CODE' => 'home',
                'SERVICE_LABEL' => 'Home Delivery',
                'ZONES' => ['SE', 'NORDIC'],
                'RATE_MINOR' => 1290,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
            'bring-service-point' => [
                'LABEL' => 'Bring Service Point',
                'CARRIER' => 'bring',
                'SERVICE_CODE' => 'service_point',
                'SERVICE_LABEL' => 'Service Point',
                'ZONES' => ['SE', 'NORDIC'],
                'RATE_MINOR' => 1390,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'dhl-service-point' => [
                'LABEL' => 'DHL Service Point',
                'CARRIER' => 'dhl',
                'SERVICE_CODE' => 'service_point',
                'SERVICE_LABEL' => 'Service Point',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
                'RATE_MINOR' => 1590,
                'SERVICE_POINT_REQUIRED' => true,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'schenker-parcel' => [
                'LABEL' => 'Schenker Parcel',
                'CARRIER' => 'schenker',
                'SERVICE_CODE' => 'parcel',
                'SERVICE_LABEL' => 'Parcel Delivery',
                'ZONES' => ['SE', 'NORDIC', 'EU'],
                'RATE_MINOR' => 1490,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'earlybird-mailbox' => [
                'LABEL' => 'Early Bird Mailbox',
                'CARRIER' => 'earlybird',
                'SERVICE_CODE' => 'mailbox',
                'SERVICE_LABEL' => 'Mailbox Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 790,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => true,
            ],
            'airmee-home' => [
                'LABEL' => 'Airmee Home',
                'CARRIER' => 'airmee',
                'SERVICE_CODE' => 'home',
                'SERVICE_LABEL' => 'Evening Home Delivery',
                'ZONES' => ['SE'],
                'RATE_MINOR' => 1690,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
            'ups-standard' => [
                'LABEL' => 'UPS Standard',
                'CARRIER' => 'ups',
                'SERVICE_CODE' => 'standard',
                'SERVICE_LABEL' => 'Standard Delivery',
                'ZONES' => ['EU', 'INTL'],
                'RATE_MINOR' => 2490,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
            'dhl-express' => [
                'LABEL' => 'DHL Express',
                'CARRIER' => 'dhl',
                'SERVICE_CODE' => 'express',
                'SERVICE_LABEL' => 'Express Delivery',
                'ZONES' => ['EU', 'INTL'],
                'RATE_MINOR' => 2990,
                'SERVICE_POINT_REQUIRED' => false,
                'FREE_SHIPPING_ELIGIBLE' => false,
            ],
        ],
    ],
    'DISCOUNT' => [
        'RATE_BPS' => 0,
        'MAX_MINOR' => 0,
    ],
    'PROMOTIONS' => [
        'VALKOMMEN10' => [
            'LABEL' => 'Valkommen 10%',
            'DESCRIPTION' => 'A gentle first-order style discount on the cart subtotal.',
            'TYPE' => 'percentage',
            'RATE_BPS' => 1000,
            'MAX_DISCOUNT_MINOR' => 3000,
            'MIN_SUBTOTAL_MINOR' => 5000,
            'ALLOWED_COUNTRIES' => ['SE', 'NO', 'DK', 'FI'],
            'ALLOWED_ZONES' => ['SE', 'NORDIC'],
        ],
        'START100' => [
            'LABEL' => 'Start 100 kr',
            'DESCRIPTION' => 'Fixed launch discount for larger baskets.',
            'TYPE' => 'fixed_amount',
            'AMOUNT_MINOR' => 10000,
            'MIN_SUBTOTAL_MINOR' => 15000,
            'ALLOWED_COUNTRIES' => ['SE'],
            'ALLOWED_ZONES' => ['SE'],
        ],
        'FRIFRAKT' => [
            'LABEL' => 'Fri Frakt',
            'DESCRIPTION' => 'Free shipping on service-point and other free-shipping eligible methods.',
            'TYPE' => 'free_shipping',
            'MIN_SUBTOTAL_MINOR' => 5000,
            'FREE_SHIPPING_ELIGIBLE_ONLY' => true,
            'ALLOWED_COUNTRIES' => ['SE'],
            'ALLOWED_ZONES' => ['SE'],
        ],
        'LOCKER49' => [
            'LABEL' => 'Locker 49 kr',
            'DESCRIPTION' => 'Reduces selected Swedish locker deliveries to 49 kr.',
            'TYPE' => 'shipping_fixed',
            'SHIPPING_RATE_MINOR' => 490,
            'ALLOWED_COUNTRIES' => ['SE'],
            'ALLOWED_ZONES' => ['SE'],
            'ALLOWED_CARRIERS' => ['instabox', 'budbee', 'postnord'],
            'ALLOWED_SHIPPING_OPTIONS' => ['instabox-locker', 'budbee-box', 'postnord-service-point'],
        ],
        'DIGITAL25' => [
            'LABEL' => 'Digital 25%',
            'DESCRIPTION' => 'Criteria-based percentage discount for digital downloads and virtual access products.',
            'TYPE' => 'percentage',
            'APPLIES_TO' => 'qualified_items',
            'RATE_BPS' => 2500,
            'MAX_DISCOUNT_MINOR_BY_CURRENCY' => [
                'SEK' => 5000,
                'EUR' => 500,
            ],
            'ALLOWED_FULFILLMENT_TYPES' => ['digital_download', 'virtual_access'],
            'ALLOWED_CURRENCIES' => ['SEK', 'EUR'],
        ],
        'SEK250' => [
            'LABEL' => '250 kr exact discount',
            'DESCRIPTION' => 'Currency-specific exact amount discount for larger Swedish baskets.',
            'TYPE' => 'fixed_amount',
            'AMOUNT_MINOR_BY_CURRENCY' => [
                'SEK' => 25000,
            ],
            'MIN_SUBTOTAL_MINOR_BY_CURRENCY' => [
                'SEK' => 100000,
            ],
            'ALLOWED_CURRENCIES' => ['SEK'],
        ],
        'MIXED15' => [
            'LABEL' => 'Mixed cart 15%',
            'DESCRIPTION' => 'Criteria-based subtotal discount when the cart combines physical and digital fulfillment.',
            'TYPE' => 'percentage',
            'RATE_BPS' => 1500,
            'MIN_ITEMS' => 2,
            'REQUIRED_FULFILLMENT_TYPES' => ['physical_shipping', 'digital_download'],
            'ALLOWED_CURRENCIES' => ['SEK'],
        ],
    ],
    'INVENTORY' => [
        'RESERVE_ON_CHECKOUT' => true,
        'RELEASE_ON_CANCEL' => true,
        'RESERVATION_TTL_MINUTES' => 60,
    ],
    'FULFILLMENT' => [
        'DEFAULT_TYPE' => 'physical_shipping',
        'AUTO_READY_ON_CAPTURE' => true,
        'TYPES' => [
            'physical_shipping' => [
                'LABEL' => 'Physical shipping',
                'DESCRIPTION' => 'Carrier-delivered physical goods.',
                'REQUIRES_SHIPPING' => true,
                'REQUIRES_STOCK' => true,
            ],
            'digital_download' => [
                'LABEL' => 'Digital download',
                'DESCRIPTION' => 'Downloadable file or license delivered after payment.',
                'REQUIRES_SHIPPING' => false,
                'REQUIRES_STOCK' => false,
            ],
            'virtual_access' => [
                'LABEL' => 'Virtual / online access',
                'DESCRIPTION' => 'Online access, gated content, courses, memberships, or streamed experiences.',
                'REQUIRES_SHIPPING' => false,
                'REQUIRES_STOCK' => false,
            ],
            'store_pickup' => [
                'LABEL' => 'Pickup at store',
                'DESCRIPTION' => 'Customer collects the order at a configured store location.',
                'REQUIRES_SHIPPING' => false,
                'REQUIRES_STOCK' => true,
            ],
            'scheduled_pickup' => [
                'LABEL' => 'Scheduled pickup',
                'DESCRIPTION' => 'Customer books a pickup date or time window.',
                'REQUIRES_SHIPPING' => false,
                'REQUIRES_STOCK' => true,
            ],
            'preorder' => [
                'LABEL' => 'Pre-order',
                'DESCRIPTION' => 'Purchasable before stock release or fulfillment availability.',
                'REQUIRES_SHIPPING' => true,
                'REQUIRES_STOCK' => false,
            ],
            'subscription' => [
                'LABEL' => 'Subscription / recurring',
                'DESCRIPTION' => 'Recurring access or billing lifecycle handled through subscription workflows.',
                'REQUIRES_SHIPPING' => false,
                'REQUIRES_STOCK' => false,
            ],
        ],
        'NO_SHIPPING_TYPES' => ['digital_download', 'virtual_access', 'subscription'],
        'SHIPPING_REQUIRED_TYPES' => ['physical_shipping', 'preorder'],
        'PICKUP_TYPES' => ['store_pickup', 'scheduled_pickup'],
        'STOCK_MANAGED_TYPES' => ['physical_shipping', 'store_pickup', 'scheduled_pickup'],
        'DIGITAL_DELIVERY_OPTION' => [
            'CODE' => 'digital-delivery',
            'LABEL' => 'Digital / online delivery',
            'SERVICE_LABEL' => 'Instant access after payment',
        ],
        'ACCESS' => [
            'ELIGIBLE_TYPES' => ['digital_download', 'virtual_access', 'subscription'],
            'ISSUE_ON_PAYMENT_STATUSES' => ['captured', 'partially_captured'],
            'REVOKE_ON_PAYMENT_STATUSES' => ['cancelled', 'refunded'],
            'DEFAULT_DOWNLOAD_LIMIT' => 0,
            'DEFAULT_ACCESS_DAYS' => 0,
            'ACCESS_KEY_PREFIX' => 'ent',
        ],
        'PICKUP_OPTIONS' => [
            'store-pickup' => [
                'LABEL' => 'Pickup at store',
                'SERVICE_CODE' => 'store_pickup',
                'SERVICE_LABEL' => 'Store pickup',
                'RATE_MINOR' => 0,
                'COUNTRIES' => ['SE'],
                'ZONES' => ['SE'],
                'LOCATION_REQUIRED' => true,
                'SCHEDULE_REQUIRED' => false,
            ],
            'scheduled-pickup' => [
                'LABEL' => 'Book pickup at store',
                'SERVICE_CODE' => 'scheduled_pickup',
                'SERVICE_LABEL' => 'Scheduled pickup',
                'RATE_MINOR' => 0,
                'COUNTRIES' => ['SE'],
                'ZONES' => ['SE'],
                'LOCATION_REQUIRED' => true,
                'SCHEDULE_REQUIRED' => true,
            ],
        ],
        'SUBSCRIPTIONS' => [
            'DEFAULT_INTERVAL' => 'monthly',
            'SUPPORTED_INTERVALS' => ['weekly', 'monthly', 'quarterly', 'yearly'],
            'TRIAL_DAYS' => 0,
            'MAX_RETRIES' => 3,
            'DUNNING_RETRY_DAYS' => [1, 3, 7],
        ],
    ],
];
