<?php

declare(strict_types=1);

return [
    'DRIVER' => 'testing',
    'CURRENCY' => 'SEK',
    'DEFAULT_METHOD' => 'card',
    'DEFAULT_FLOW' => 'authorize_capture',
    'WEBHOOKS' => [
        'ENABLED' => true,
        'REQUIRE_SIGNATURE' => true,
        'SIGNATURE_HEADER' => 'X-Langeler-Signature',
        'EVENT_ID_HEADER' => 'X-Langeler-Event',
        'TIMESTAMP_HEADER' => 'X-Langeler-Timestamp',
        'TOLERANCE_SECONDS' => 300,
        'SECRETS' => [
            'testing' => '',
            'card' => '',
            'crypto' => '',
            'paypal' => '',
            'klarna' => '',
            'swish' => '',
            'qliro' => '',
            'walley' => '',
        ],
    ],
    'DRIVERS' => [
        'testing' => [
            'ENABLED' => true,
            'LABEL' => 'Testing Reference Driver',
            'MODE' => 'reference',
            'DOCS_URL' => 'https://github.com/joakim/langelermvc',
            'REGIONS' => ['GLOBAL'],
            'DEFAULT_METHOD' => 'card',
            'DEFAULT_FLOW' => 'authorize_capture',
            'METHODS' => [
                'card',
                'wallet',
                'bank_transfer',
                'bnpl',
                'local_instant',
                'manual',
                'crypto',
            ],
            'FLOWS' => [
                'authorize_capture',
                'purchase',
                'redirect',
                'async',
                'manual_review',
            ],
        ],
        'card' => [
            'ENABLED' => true,
            'LABEL' => 'Credit / Debit Card',
            'MODE' => 'reference',
            'DOCS_URL' => null,
            'REGIONS' => ['GLOBAL'],
            'DEFAULT_METHOD' => 'card',
            'DEFAULT_FLOW' => 'authorize_capture',
            'METHODS' => ['card'],
            'FLOWS' => ['authorize_capture', 'purchase', 'redirect'],
            'AUTH_SCHEME' => 'Bearer',
            'API_BASE' => '',
            'API_KEY' => '',
            'CREATE_URL' => '',
            'CAPTURE_URL' => '',
            'REFUND_URL' => '',
            'CANCEL_URL' => '',
            'RECONCILE_URL' => '',
        ],
        'crypto' => [
            'ENABLED' => true,
            'LABEL' => 'Crypto',
            'MODE' => 'reference',
            'DOCS_URL' => null,
            'REGIONS' => ['GLOBAL'],
            'DEFAULT_METHOD' => 'crypto',
            'DEFAULT_FLOW' => 'async',
            'METHODS' => ['crypto'],
            'FLOWS' => ['async', 'redirect', 'manual_review'],
            'DEFAULT_ASSET' => 'BTC',
            'DEFAULT_NETWORK' => 'bitcoin',
            'CONFIRMATIONS_REQUIRED' => 1,
        ],
        'paypal' => [
            'ENABLED' => true,
            'LABEL' => 'PayPal',
            'MODE' => 'reference',
            'DOCS_URL' => 'https://developer.paypal.com/docs/api/orders/v2/',
            'REGIONS' => ['GLOBAL'],
            'DEFAULT_METHOD' => 'wallet',
            'DEFAULT_FLOW' => 'redirect',
            'METHODS' => ['wallet', 'card'],
            'FLOWS' => ['authorize_capture', 'purchase', 'redirect'],
            'API_BASE' => 'https://api-m.sandbox.paypal.com',
            'CLIENT_ID' => '',
            'CLIENT_SECRET' => '',
            'RETURN_URL' => 'https://langelermvc.test/orders/complete',
            'CANCEL_URL' => 'https://langelermvc.test/orders/cancelled',
            'BRAND_NAME' => 'LangelerMVC',
        ],
        'klarna' => [
            'ENABLED' => true,
            'LABEL' => 'Klarna',
            'MODE' => 'reference',
            'DOCS_URL' => 'https://docs.klarna.com/payments/',
            'REGIONS' => ['SE', 'NO', 'FI', 'DK', 'DE', 'AT', 'NL', 'BE', 'UK', 'US'],
            'DEFAULT_METHOD' => 'bnpl',
            'DEFAULT_FLOW' => 'redirect',
            'METHODS' => ['bnpl'],
            'FLOWS' => ['redirect', 'authorize_capture'],
            'API_BASE' => 'https://api.playground.klarna.com',
            'USERNAME' => '',
            'PASSWORD' => '',
            'PURCHASE_COUNTRY' => 'SE',
            'PURCHASE_CURRENCY' => 'SEK',
            'LOCALE' => 'sv-SE',
        ],
        'swish' => [
            'ENABLED' => true,
            'LABEL' => 'Swish',
            'MODE' => 'reference',
            'DOCS_URL' => 'https://developer.swish.nu/',
            'REGIONS' => ['SE'],
            'DEFAULT_METHOD' => 'local_instant',
            'DEFAULT_FLOW' => 'redirect',
            'METHODS' => ['local_instant'],
            'FLOWS' => ['redirect', 'async'],
            'API_BASE' => 'https://mss.cpc.getswish.net/swish-cpcapi/api/v2',
            'PAYEE_ALIAS' => '',
            'CERTIFICATE_PATH' => '',
            'PRIVATE_KEY_PATH' => '',
            'PASSPHRASE' => '',
            'CALLBACK_URL' => 'https://langelermvc.test/payments/swish/callback',
        ],
        'qliro' => [
            'ENABLED' => true,
            'LABEL' => 'Qliro',
            'MODE' => 'reference',
            'DOCS_URL' => 'https://developers.qliro.com/docs',
            'REGIONS' => ['SE', 'NO', 'FI', 'DK'],
            'DEFAULT_METHOD' => 'bnpl',
            'DEFAULT_FLOW' => 'redirect',
            'METHODS' => ['card', 'bnpl', 'local_instant', 'bank_transfer'],
            'FLOWS' => ['redirect', 'authorize_capture'],
            'API_BASE' => 'https://api.qit.nu',
            'API_KEY' => '',
            'MERCHANT_API_KEY' => '',
            'MERCHANT_API_SECRET' => '',
            'MERCHANT_CONFIRMATION_URL' => 'https://langelermvc.test/orders/complete',
            'MERCHANT_TERMS_URL' => 'https://langelermvc.test/terms',
            'MERCHANT_CHECKOUT_STATUS_PUSH_URL' => '',
            'MERCHANT_ORDER_MANAGEMENT_STATUS_PUSH_URL' => '',
            'CAPTURE_URL' => '',
            'REFUND_URL' => '',
            'CANCEL_URL' => '',
        ],
        'walley' => [
            'ENABLED' => true,
            'LABEL' => 'Walley',
            'MODE' => 'reference',
            'DOCS_URL' => 'https://dev.walleypay.com/paymentsApi/',
            'REGIONS' => ['SE', 'NO', 'FI', 'DK'],
            'DEFAULT_METHOD' => 'bnpl',
            'DEFAULT_FLOW' => 'redirect',
            'METHODS' => ['bnpl'],
            'FLOWS' => ['redirect', 'authorize_capture'],
            'API_BASE' => '',
            'API_KEY' => '',
            'WSDL_URL' => '',
            'USERNAME' => '',
            'PASSWORD' => '',
            'MERCHANT_ID' => '',
            'RETURN_URL' => 'https://langelermvc.test/orders/complete',
            'CALLBACK_URL' => '',
            'CREATE_URL' => '',
            'CAPTURE_URL' => '',
            'REFUND_URL' => '',
            'CANCEL_URL' => '',
            'RECONCILE_URL' => '',
        ],
    ],
];
